# A list of worlds where you cannot trade with players.
disabledWorlds: []

# A list of sources for products
stockLocations:
  - inventory
  - enderchest

# Automatically thank a player for a purchase
autoThanks: true

# Selected language (see the languages folder for a list of languages (or make your own inside that folder)
currentLanguage: en_us