# A list of worlds where you cannot trade with players.
disabledWorlds: []

# A list of sources for products
stockLocations:
  - inventory
  - enderchest

# Automatically thank a player for a purchase
autoThanks: true

# Selected language (see the languages folder for a list of languages (or make your own inside that folder))
currentLanguage: en_us

# Database
database:
  type: sqlite # Database Type (supported values are "sqlite" and "mysql")
  file: database.db # Name of database file (sqlite only)
  prefix: spt # _ is not added by default (sqlite and mysql) - do not change once set
#  host: localhost # Host of database (mysql only)
#  port: 3306 # Port number of database (mysql only)
#  name: sptdatabase # Name of database (mysql only)
#  username: root # Username of database user (mysql only)
#  password: "" # Password of database user (mysql only)

# Check for updates
checkForUpdates: true

# Check for known bugs and warn you about them
checkForBugs:
  check: false # Checks for known bugs, and warns you about them
  disable: false # Disables the plugin automatically if a possibly bad bug (such as a duplication bug) is found

# Enables/Disables the GUI Manager
useGuiManager: true

# Automatically toggle off while in combat
autoCombatLock:
  enabled: true # Enables/Disables auto combat toggling
  combatLockLength: 30 # Combat lock length (in seconds)
  neverShowNotice: false # Enables/Disables the toggle notice (if this is false, the players can choose for themselves)